Update readme
IslasGECI/jenkins pull request #2
Opened 2022-03-01 23:22 UTC by xwalls

2022-03-02 18:01 UTC, xwalls commented
1. Actualizar dependencias del servidor `apt update`
2. Instalar docker en el servidor `apt install --yes docker.io`
3. asdd
```
sudo adduser jenkins
sudo usermod -aG docker jenkins
sudo usermod -aG root jenkins
sudo chmod 777 /var/run/docker.sock
```

5. Configurar el archivo `~/.vault/.secrets`
5. 
```
docker pull islasgeci/jenkins:latest
docker run \
    --detach \
    --name jenkins \
    --publish 50000:50000 \
    --publish 8080:8080 \
    --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume ${HOME}/.vault/.secrets:/.vault/.secrets \
    --volume jenkins_home:/var/jenkins_home \
    islasgeci/jenkins:latest
```
6. `docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword`
7. En el navegador ir a `IP_SERVIDOR:8080`. Se nos pedira la clave del `paso 6`
8. Instalar plugins recomendados
![image](https://user-images.githubusercontent.com/9456708/156418548-9f063548-8275-49e4-93c4-2ee2640e8563.png)

9. Crear la cuenta maestra de jenkins
![image](https://user-images.githubusercontent.com/9456708/156416692-1a18df25-66fb-4b35-9be4-6ab00d1e6aba.png)
10. Terminar configuracion. `http://IP_SERVIDOR:8080/`
![image](https://user-images.githubusercontent.com/9456708/156416920-baae05d6-b17e-48a0-9175-08cc8352c518.png)

2022-03-08 16:47 UTC, xwalls commented
## Pasos que no seran respansabilidad de este repositorio (1-5):

1. Actualizar dependencias del servidor `apt update`
2. Instalar docker en el servidor `apt install --yes docker.io`
3. Configurar el usuario de jenkins
```
sudo adduser jenkins
sudo usermod -aG docker jenkins
sudo usermod -aG root jenkins
```

4. Dar permisos al servicio de docker
```
sudo chmod 777 /var/run/docker.sock
```
5. Configurar el archivo `~/.vault/.secrets`

## Con los pasos anteriores hechos:
1. Si tenemos un servidor nuevo, debemos cambiar los `secretos` en el actions de **Github** (`SERVER_HOST_IP` y `SERVER _PASSWORD`)
2. Podemos activar nuestro actions para que el jenkins sea desplegado en el servidor.
3. El jenkins y los plugins seran instalados automaticamente.
4. Entrar al jenkins mediante la ruta `http://SERVER_HOST_IP:8080`

2022-03-11 20:48 UTC, nepito requested changes
Hola @xwalls, esperaba ver algunos cambios en el README y no los vi ¿Me equivoqué de repo?

2022-03-11 20:48 UTC, nepito commented on .github/workflows/develop.yml
> +        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
Por favor agrega la versión larga de la opción. Creo que es esta:
```suggestion
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
```

2022-03-11 20:51 UTC, nepito requested changes
Por favor agrega [estos comentarios](https://github.com/IslasGECI/jenkins/pull/2#issuecomment-1061984258) al README. Aunque tal vez vayan en otro repo, ¿verdad?

2022-04-01 16:05 UTC, nepito commented
Aquí están los precios:
![image](https://user-images.githubusercontent.com/35377740/161300329-e3c1794c-2120-45a3-82ed-ec2411e5bd0a.png)

El droplet más poderoso cuesta 48 dolares al mes. Si solo lo usamos de lunes a viernes en el horario de trabajo, pagaríamos menos de 3 dólares a la semana.

2022-04-04 15:10 UTC, nepito commented
12 horas a la semana al día en una semana de cinco días (60 horas a la semana). Esto durante un año (52 semanas) por el precio de $0.071 la hora. En total serán 3120 horas y nos costará ~$230.

2022-06-03 21:58 UTC, closed without merging